import type { Project } from "./types"

const PROJECT_IMAGES = [
  "/office-work-laptop-professional.jpg",
  "/business-meeting-team-collaboration.jpg",
  "/data-analytics-dashboard-screens.jpg",
  "/legal-documents-courthouse-justice.jpg",
  "/technology-server-room-digital.jpg",
  "/people-handshake-business-deal.jpg",
  "/modern-office-building.png",
  "/team-brainstorming-whiteboard-ideas.jpg",
  "/computer-coding-programming-screen.jpg",
  "/family-consultation-meeting-room.jpg",
  "/courtroom-legal-proceeding-gavel.jpg",
  "/digital-transformation-technology-abstract.jpg",
  "/public-service-government-building.jpg",
  "/documents-paperwork-filing-cabinet.jpg",
  "/video-conference-remote-meeting.jpg",
  "/customer-service-helpdesk-support.jpg",
  "/mobile-app-smartphone-interface.jpg",
  "/cloud-computing-infrastructure-network.jpg",
  "/placeholder.svg?height=400&width=600",
  "/placeholder.svg?height=400&width=600",
  "/placeholder.svg?height=400&width=600",
  "/placeholder.svg?height=400&width=600",
  "/placeholder.svg?height=400&width=600",
  "/placeholder.svg?height=400&width=600",
  "/placeholder.svg?height=400&width=600",
  "/placeholder.svg?height=400&width=600",
  "/placeholder.svg?height=400&width=600",
]

export const MOCK_PROJECTS: Project[] = [
  // CÍVEL (6 projetos)
  {
    id: "1",
    name: "Sistema de Peticionamento Digital",
    description: "Plataforma para envio e acompanhamento de petições eletrônicas com assinatura digital integrada.",
    area: "civel",
    status: "em_andamento",
    progress: 75,
    startDate: "2024-01-15",
    endDate: "2025-03-30",
    priority: "alta",
    featured: true,
    image: PROJECT_IMAGES[0],
    team: [
      { id: "t1", name: "Ana Silva", role: "Coordenadora" },
      { id: "t2", name: "Carlos Mendes", role: "Desenvolvedor" },
      { id: "t3", name: "Maria Santos", role: "Analista Jurídico" },
    ],
  },
  {
    id: "2",
    name: "Banco de Jurisprudência",
    description: "Repositório digital de decisões judiciais com busca inteligente por palavras-chave e temas.",
    area: "civel",
    status: "concluido",
    progress: 100,
    startDate: "2023-06-01",
    endDate: "2024-02-28",
    priority: "media",
    image: PROJECT_IMAGES[1],
    team: [
      { id: "t4", name: "Roberto Lima", role: "Coordenador" },
      { id: "t5", name: "Juliana Costa", role: "Pesquisadora" },
    ],
  },
  {
    id: "3",
    name: "Automação de Cálculos Cíveis",
    description: "Ferramenta para cálculo automático de correção monetária, juros e honorários advocatícios.",
    area: "civel",
    status: "planejado",
    progress: 10,
    startDate: "2025-04-01",
    endDate: "2025-09-30",
    priority: "media",
    image: PROJECT_IMAGES[2],
    team: [{ id: "t6", name: "Fernando Gomes", role: "Coordenador" }],
  },
  {
    id: "4",
    name: "Portal do Assistido - Cível",
    description: "Interface web para assistidos acompanharem seus processos cíveis em tempo real.",
    area: "civel",
    status: "em_andamento",
    progress: 45,
    startDate: "2024-08-01",
    endDate: "2025-06-30",
    priority: "alta",
    image: PROJECT_IMAGES[3],
    team: [
      { id: "t7", name: "Patrícia Alves", role: "UX Designer" },
      { id: "t8", name: "Lucas Ferreira", role: "Desenvolvedor Front-end" },
    ],
  },
  {
    id: "5",
    name: "Gestão de Prazos Processuais",
    description: "Sistema de alertas e controle de prazos para evitar preclusões e garantir tempestividade.",
    area: "civel",
    status: "atrasado",
    progress: 30,
    startDate: "2024-03-01",
    endDate: "2024-12-31",
    priority: "alta",
    image: PROJECT_IMAGES[4],
    team: [{ id: "t9", name: "Marcos Ribeiro", role: "Analista de Sistemas" }],
  },
  {
    id: "6",
    name: "Integração com Tribunais",
    description: "API de integração com sistemas PJe e e-SAJ para consulta e movimentação processual.",
    area: "civel",
    status: "pausado",
    progress: 55,
    startDate: "2024-02-15",
    endDate: "2025-01-31",
    priority: "media",
    image: PROJECT_IMAGES[5],
    team: [
      { id: "t10", name: "Diego Santos", role: "Arquiteto de Software" },
      { id: "t11", name: "Camila Oliveira", role: "Desenvolvedora Backend" },
    ],
  },

  // CRIMINAL (5 projetos)
  {
    id: "7",
    name: "Sistema de Audiências de Custódia",
    description: "Plataforma para gestão e acompanhamento de audiências de custódia com videoconferência integrada.",
    area: "criminal",
    status: "em_andamento",
    progress: 60,
    startDate: "2024-04-01",
    endDate: "2025-04-30",
    priority: "alta",
    featured: true,
    image: PROJECT_IMAGES[6],
    team: [
      { id: "t12", name: "Ricardo Nunes", role: "Coordenador" },
      { id: "t13", name: "Beatriz Souza", role: "Defensora Criminal" },
      { id: "t14", name: "André Lima", role: "Desenvolvedor" },
    ],
  },
  {
    id: "8",
    name: "Banco de Dados de Execução Penal",
    description: "Sistema para controle de benefícios, progressões e remições de pena dos assistidos.",
    area: "criminal",
    status: "em_andamento",
    progress: 85,
    startDate: "2023-09-01",
    endDate: "2025-02-28",
    priority: "alta",
    image: PROJECT_IMAGES[7],
    team: [
      { id: "t15", name: "Vanessa Rocha", role: "Coordenadora" },
      { id: "t16", name: "Paulo César", role: "Desenvolvedor" },
    ],
  },
  {
    id: "9",
    name: "App Visita Virtual",
    description: "Aplicativo mobile para realização de visitas virtuais em unidades prisionais.",
    area: "criminal",
    status: "planejado",
    progress: 5,
    startDate: "2025-06-01",
    endDate: "2026-03-31",
    priority: "media",
    image: PROJECT_IMAGES[8],
    team: [{ id: "t17", name: "Thiago Martins", role: "Product Owner" }],
  },
  {
    id: "10",
    name: "Mutirão Carcerário Digital",
    description: "Ferramenta para organização e execução de mutirões de revisão de processos criminais.",
    area: "criminal",
    status: "concluido",
    progress: 100,
    startDate: "2023-01-15",
    endDate: "2024-06-30",
    priority: "alta",
    image: PROJECT_IMAGES[9],
    team: [
      { id: "t18", name: "Leandro Costa", role: "Coordenador" },
      { id: "t19", name: "Fernanda Dias", role: "Defensora" },
    ],
  },
  {
    id: "11",
    name: "Integração SEAP",
    description: "Conexão direta com sistemas da Secretaria de Administração Penitenciária.",
    area: "criminal",
    status: "pendente",
    progress: 0,
    startDate: "2025-03-01",
    endDate: "2025-12-31",
    priority: "media",
    image: PROJECT_IMAGES[10],
    team: [{ id: "t20", name: "Gabriel Reis", role: "Analista de Integração" }],
  },

  // FAMÍLIA (5 projetos)
  {
    id: "12",
    name: "Plataforma de Mediação Familiar",
    description: "Sistema online para sessões de mediação com recursos de videoconferência e documentação.",
    area: "familia",
    status: "em_andamento",
    progress: 40,
    startDate: "2024-07-01",
    endDate: "2025-07-31",
    priority: "alta",
    featured: true,
    image: PROJECT_IMAGES[11],
    team: [
      { id: "t21", name: "Cristina Melo", role: "Coordenadora" },
      { id: "t22", name: "Eduardo Pinto", role: "Desenvolvedor Full-stack" },
      { id: "t23", name: "Renata Campos", role: "Mediadora" },
    ],
  },
  {
    id: "13",
    name: "Calculadora de Alimentos",
    description: "Ferramenta para cálculo de pensão alimentícia baseada em parâmetros legais e jurisprudenciais.",
    area: "familia",
    status: "concluido",
    progress: 100,
    startDate: "2024-01-01",
    endDate: "2024-08-31",
    priority: "media",
    image: PROJECT_IMAGES[12],
    team: [{ id: "t24", name: "Simone Barros", role: "Desenvolvedora" }],
  },
  {
    id: "14",
    name: "Sistema de Adoção",
    description: "Plataforma para gestão do processo de habilitação e acompanhamento de adoções.",
    area: "familia",
    status: "planejado",
    progress: 15,
    startDate: "2025-02-01",
    endDate: "2026-02-28",
    priority: "alta",
    image: PROJECT_IMAGES[13],
    team: [
      { id: "t25", name: "Mariana Duarte", role: "Coordenadora" },
      { id: "t26", name: "Felipe Araújo", role: "Analista de Requisitos" },
    ],
  },
  {
    id: "15",
    name: "Guarda Compartilhada - Gestão",
    description: "Aplicativo para gestão de calendário e comunicação entre pais em regime de guarda compartilhada.",
    area: "familia",
    status: "pendente",
    progress: 0,
    startDate: "2025-08-01",
    endDate: "2026-06-30",
    priority: "baixa",
    image: PROJECT_IMAGES[14],
    team: [{ id: "t27", name: "Daniela Freitas", role: "Product Manager" }],
  },
  {
    id: "16",
    name: "Portal de Orientação Familiar",
    description: "Website com informações jurídicas e orientações para famílias em situação de conflito.",
    area: "familia",
    status: "em_andamento",
    progress: 70,
    startDate: "2024-05-01",
    endDate: "2025-01-31",
    priority: "media",
    image: PROJECT_IMAGES[15],
    team: [
      { id: "t28", name: "Luciana Ramos", role: "Redatora Jurídica" },
      { id: "t29", name: "Igor Nascimento", role: "Web Designer" },
    ],
  },

  // ADMINISTRATIVO (5 projetos)
  {
    id: "17",
    name: "Sistema de Gestão de Pessoas",
    description: "Plataforma completa para RH: ponto eletrônico, férias, capacitações e avaliações.",
    area: "administrativo",
    status: "em_andamento",
    progress: 55,
    startDate: "2024-03-01",
    endDate: "2025-05-31",
    priority: "alta",
    featured: true,
    image: PROJECT_IMAGES[16],
    team: [
      { id: "t30", name: "Rogério Tavares", role: "Coordenador" },
      { id: "t31", name: "Aline Machado", role: "Analista de RH" },
      { id: "t32", name: "Bruno Carvalho", role: "Desenvolvedor" },
    ],
  },
  {
    id: "18",
    name: "Controle de Patrimônio",
    description: "Sistema para inventário e gestão de bens móveis e imóveis da Defensoria.",
    area: "administrativo",
    status: "concluido",
    progress: 100,
    startDate: "2023-08-01",
    endDate: "2024-04-30",
    priority: "media",
    image: PROJECT_IMAGES[17],
    team: [{ id: "t33", name: "Helena Cardoso", role: "Coordenadora" }],
  },
  {
    id: "19",
    name: "Portal de Transparência 2.0",
    description: "Atualização do portal com novos indicadores e visualizações de dados públicos.",
    area: "administrativo",
    status: "atrasado",
    progress: 25,
    startDate: "2024-06-01",
    endDate: "2024-11-30",
    priority: "alta",
    image: PROJECT_IMAGES[18],
    team: [
      { id: "t34", name: "Otávio Mendes", role: "Desenvolvedor" },
      { id: "t35", name: "Tatiana Lima", role: "Data Analyst" },
    ],
  },
  {
    id: "20",
    name: "E-Protocolo",
    description: "Sistema eletrônico de protocolo e tramitação de documentos administrativos.",
    area: "administrativo",
    status: "em_andamento",
    progress: 80,
    startDate: "2024-01-01",
    endDate: "2025-02-28",
    priority: "media",
    image: PROJECT_IMAGES[19],
    team: [{ id: "t36", name: "Sérgio Oliveira", role: "Coordenador" }],
  },
  {
    id: "21",
    name: "Dashboard Gerencial",
    description: "Painel de indicadores de desempenho institucional para a alta administração.",
    area: "administrativo",
    status: "planejado",
    progress: 5,
    startDate: "2025-05-01",
    endDate: "2025-10-31",
    priority: "alta",
    image: PROJECT_IMAGES[20],
    team: [{ id: "t37", name: "Marcelo Freire", role: "BI Analyst" }],
  },

  // TECNOLOGIA (6 projetos)
  {
    id: "22",
    name: "Infraestrutura Cloud",
    description: "Migração da infraestrutura on-premise para ambiente de nuvem híbrida.",
    area: "tecnologia",
    status: "em_andamento",
    progress: 65,
    startDate: "2024-02-01",
    endDate: "2025-06-30",
    priority: "alta",
    featured: true,
    image: PROJECT_IMAGES[21],
    team: [
      { id: "t38", name: "Alexandre Souza", role: "Cloud Architect" },
      { id: "t39", name: "Priscila Matos", role: "DevOps Engineer" },
      { id: "t40", name: "Rafael Torres", role: "SRE" },
    ],
  },
  {
    id: "23",
    name: "Assistente Virtual IA",
    description: "Chatbot com inteligência artificial para atendimento inicial e triagem de demandas.",
    area: "tecnologia",
    status: "em_andamento",
    progress: 35,
    startDate: "2024-09-01",
    endDate: "2025-08-31",
    priority: "alta",
    image: PROJECT_IMAGES[22],
    team: [
      { id: "t41", name: "Vinícius Almeida", role: "ML Engineer" },
      { id: "t42", name: "Carla Rodrigues", role: "NLP Specialist" },
    ],
  },
  {
    id: "24",
    name: "Segurança Cibernética",
    description: "Implementação de SIEM, SOC e políticas de segurança da informação.",
    area: "tecnologia",
    status: "em_andamento",
    progress: 50,
    startDate: "2024-04-01",
    endDate: "2025-04-30",
    priority: "alta",
    image: PROJECT_IMAGES[23],
    team: [
      { id: "t43", name: "Gustavo Henrique", role: "Security Analyst" },
      { id: "t44", name: "Amanda Correia", role: "Pentester" },
    ],
  },
  {
    id: "25",
    name: "API Gateway Institucional",
    description: "Plataforma centralizada para gestão e exposição de APIs internas e externas.",
    area: "tecnologia",
    status: "pausado",
    progress: 40,
    startDate: "2024-05-15",
    endDate: "2025-03-31",
    priority: "media",
    image: PROJECT_IMAGES[24],
    team: [{ id: "t45", name: "Leonardo Barbosa", role: "API Architect" }],
  },
  {
    id: "26",
    name: "Data Lake Jurídico",
    description: "Repositório centralizado de dados para análises avançadas e machine learning.",
    area: "tecnologia",
    status: "planejado",
    progress: 10,
    startDate: "2025-07-01",
    endDate: "2026-06-30",
    priority: "media",
    image: PROJECT_IMAGES[25],
    team: [{ id: "t46", name: "Isabela Cunha", role: "Data Engineer" }],
  },
  {
    id: "27",
    name: "Modernização do Legado",
    description: "Refatoração e migração de sistemas legados para arquitetura moderna de microserviços.",
    area: "tecnologia",
    status: "pendente",
    progress: 0,
    startDate: "2025-09-01",
    endDate: "2027-08-31",
    priority: "alta",
    image: PROJECT_IMAGES[26],
    team: [{ id: "t47", name: "Roberto Fonseca", role: "Tech Lead" }],
  },
]

// Funções preparadas para migração Supabase
// Substitua o corpo dessas funções por queries do Supabase

export const SEED_PROJECTS = MOCK_PROJECTS
